development:
  :address: smtp.gmail.com
  :port: 587 
  :authentication: plain
  :user_name: oneroom@wafflestudio.com
  :password: dnjsfnz1234
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587 
  :authentication: plain
  :user_name: oneroom@wafflestudio.com
  :password: dnjsfnz1234
  :enable_starttls_auto: true
