development:
  host: localhost
  database: yyhpys_oneroom_development
  options:
    raise_not_found_error: false

test:
  host: localhost
  database: yyhpys_oneroom_test

# set these environment variables on your prod server
production:
  host: localhost
  username: oneroom
  password: dnjsfna
  database: yyhpys_oneroom_production
  options:
    raise_not_found_error: false

