development:
  host: localhost
  database: yyhpys_oneroom_development
  options:
    raise_not_found_error: false

test:
  host: localhost
  database: yyhpys_oneroom_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  options:
    raise_not_found_error: false

